import PublicNav from "@/components/PublicNav";
import PublicFooter from "@/components/PublicFooter";
import { useLang } from "@/i18n/LangContext";
import type { Lang } from "@/i18n/translations";
import SEOHead from "@/components/SEOHead";

interface Section { title: string; content: string; }

const SECTIONS: Record<Lang, Section[]> = {
  fr: [
    { title: "1. Objet", content: "Les présentes Conditions Générales d'Utilisation (CGU) régissent l'accès et l'utilisation de la plateforme Mar-ia, service de création de sites web par intelligence artificielle, accessible à l'adresse maria.app." },
    { title: "2. Acceptation des CGU", content: "En accédant à la plateforme Mar-ia, vous acceptez sans réserve les présentes CGU. Si vous n'acceptez pas ces conditions, vous devez cesser d'utiliser le service." },
    { title: "3. Description du service", content: "Mar-ia est une plateforme SaaS permettant aux utilisateurs de générer, modifier et publier des sites web à l'aide de l'intelligence artificielle. Le service nécessite la connexion d'une clé API Anthropic personnelle." },
    { title: "4. Compte utilisateur", content: "L'accès au service nécessite la création d'un compte. Vous êtes responsable de la confidentialité de vos identifiants et de toutes les activités effectuées depuis votre compte." },
    { title: "5. Clés API tierces", content: "L'utilisation du service requiert une clé API Anthropic valide. Mar-ia n'est pas responsable des coûts générés par l'utilisation de votre clé API. Vous êtes seul responsable du respect des conditions d'utilisation d'Anthropic." },
    { title: "6. Propriété intellectuelle", content: "Les sites web générés via Mar-ia vous appartiennent. Vous conservez tous les droits sur le contenu que vous créez. Mar-ia conserve les droits sur sa plateforme, son interface et ses algorithmes." },
    { title: "7. Facturation et abonnements", content: "Les abonnements payants sont facturés mensuellement via Stripe. Vous pouvez annuler à tout moment. Aucun remboursement n'est accordé pour les périodes déjà facturées, sauf obligation légale." },
    { title: "8. Limitation de responsabilité", content: "Mar-ia est fourni \"tel quel\". Nous ne garantissons pas que le service sera ininterrompu ou exempt d'erreurs. Notre responsabilité est limitée au montant payé pour le service au cours des 3 derniers mois." },
    { title: "9. Résiliation", content: "Nous nous réservons le droit de suspendre ou résilier votre accès en cas de violation des présentes CGU, sans préavis ni remboursement." },
    { title: "10. Droit applicable", content: "Les présentes CGU sont soumises au droit français. Tout litige sera soumis à la compétence exclusive des tribunaux de Paris." },
  ],
  en: [
    { title: "1. Purpose", content: "These Terms of Service (ToS) govern access to and use of the Mar-ia platform, an AI-powered website creation service accessible at maria.app." },
    { title: "2. Acceptance of Terms", content: "By accessing the Mar-ia platform, you unconditionally accept these Terms. If you do not accept these terms, you must stop using the service." },
    { title: "3. Service Description", content: "Mar-ia is a SaaS platform enabling users to generate, edit and publish websites using artificial intelligence. The service requires connecting a personal Anthropic API key." },
    { title: "4. User Account", content: "Access to the service requires creating an account. You are responsible for the confidentiality of your credentials and all activities performed from your account." },
    { title: "5. Third-party API Keys", content: "Using the service requires a valid Anthropic API key. Mar-ia is not responsible for costs generated by your API key usage. You are solely responsible for complying with Anthropic's terms of use." },
    { title: "6. Intellectual Property", content: "Websites generated via Mar-ia belong to you. You retain all rights to the content you create. Mar-ia retains rights to its platform, interface and algorithms." },
    { title: "7. Billing and Subscriptions", content: "Paid subscriptions are billed monthly via Stripe. You can cancel at any time. No refunds are granted for already-billed periods, except as required by law." },
    { title: "8. Limitation of Liability", content: "Mar-ia is provided \"as is\". We do not guarantee that the service will be uninterrupted or error-free. Our liability is limited to the amount paid for the service in the last 3 months." },
    { title: "9. Termination", content: "We reserve the right to suspend or terminate your access in case of violation of these Terms, without notice or refund." },
    { title: "10. Applicable Law", content: "These Terms are governed by French law. Any dispute shall be subject to the exclusive jurisdiction of the courts of Paris." },
  ],
  es: [
    { title: "1. Objeto", content: "Los presentes Términos de Servicio (ToS) regulan el acceso y uso de la plataforma Mar-ia, servicio de creación de sitios web por inteligencia artificial, accesible en maria.app." },
    { title: "2. Aceptación de los Términos", content: "Al acceder a la plataforma Mar-ia, aceptas sin reservas los presentes Términos. Si no aceptas estas condiciones, debes dejar de usar el servicio." },
    { title: "3. Descripción del servicio", content: "Mar-ia es una plataforma SaaS que permite a los usuarios generar, editar y publicar sitios web mediante inteligencia artificial. El servicio requiere conectar una clave API personal de Anthropic." },
    { title: "4. Cuenta de usuario", content: "El acceso al servicio requiere la creación de una cuenta. Eres responsable de la confidencialidad de tus credenciales y de todas las actividades realizadas desde tu cuenta." },
    { title: "5. Claves API de terceros", content: "El uso del servicio requiere una clave API válida de Anthropic. Mar-ia no es responsable de los costes generados por el uso de tu clave API. Eres el único responsable de cumplir con las condiciones de uso de Anthropic." },
    { title: "6. Propiedad intelectual", content: "Los sitios web generados a través de Mar-ia te pertenecen. Conservas todos los derechos sobre el contenido que creas. Mar-ia conserva los derechos sobre su plataforma, interfaz y algoritmos." },
    { title: "7. Facturación y suscripciones", content: "Las suscripciones de pago se facturan mensualmente a través de Stripe. Puedes cancelar en cualquier momento. No se conceden reembolsos por períodos ya facturados, salvo obligación legal." },
    { title: "8. Limitación de responsabilidad", content: "Mar-ia se proporciona \"tal cual\". No garantizamos que el servicio sea ininterrumpido o libre de errores. Nuestra responsabilidad se limita al importe pagado por el servicio en los últimos 3 meses." },
    { title: "9. Rescisión", content: "Nos reservamos el derecho de suspender o cancelar tu acceso en caso de incumplimiento de estos Términos, sin previo aviso ni reembolso." },
    { title: "10. Ley aplicable", content: "Estos Términos se rigen por la ley francesa. Cualquier disputa estará sujeta a la jurisdicción exclusiva de los tribunales de París." },
  ],
};

const CGU_SEO = {
  fr: { title: "Conditions Générales d'Utilisation — Mar-ia", description: "Les CGU de Mar-ia : conditions d'accès, propriété intellectuelle, facturation et responsabilités." },
  en: { title: "Terms of Service — Mar-ia", description: "Mar-ia Terms of Service: access conditions, intellectual property, billing and liabilities." },
  es: { title: "Términos de Servicio — Mar-ia", description: "Términos de Servicio de Mar-ia: condiciones de acceso, propiedad intelectual, facturación y responsabilidades." },
};

export default function CGU() {
  const { lang, t } = useLang();
  const sections = SECTIONS[lang];
  const seo = CGU_SEO[lang];

  return (
    <div className="min-h-screen bg-background text-foreground">
      <SEOHead title={seo.title} description={seo.description} path="/cgu" />
      <PublicNav />
      <section className="pt-32 pb-24">
        <div className="container max-w-3xl">
          <h1 className="text-4xl font-display font-bold text-foreground mb-2">{t("cgu_title")}</h1>
          <p className="text-muted-foreground mb-10">{t("cgu_updated")}</p>

          <div className="space-y-8 text-muted-foreground">
            {sections.map((s) => (
              <section key={s.title}>
                <h2 className="text-xl font-display font-semibold text-foreground mb-3">{s.title}</h2>
                <p>{s.content}</p>
              </section>
            ))}
          </div>
        </div>
      </section>
      <PublicFooter />
    </div>
  );
}
